### ISSUE TITLE
Conflict resolution

### ISSUE THREAD

**Issue by pmelab** [amateescu/revision_tree#11]
Minimal conflict resolution framework that allows to register different resolution strategies. Tries to solve conflicts in two steps. First "automatic" resolution strategies are consulted. If all of them fail, the "manual" resolution strategies are applied.

* [Automatic conflict resolution](https://github.com/amateescu/revision_tree/tree/master/src/ConflictResolver)
* [Manual conflict resolution](https://github.com/amateescu/revision_tree/tree/master/src/ConflictResolverUI)
* [Route to initiate conflict resolution between two revisions](https://github.com/amateescu/revision_tree/blob/master/src/Controller/ConflictsResolver.php)
* [Controller to initiate conflict resolution between two revisions](https://github.com/amateescu/revision_tree/blob/master/src/Controller/ConflictsResolver.php)

*TODO:*
* Generic solution to control revision contexts of a merge revision.

**Resolution:** Move to 8.7 core?

**Comment by amateescu** [comment]
There are multiple resolutions for this.

- The basic API interface/methods should be done as a core patch. The current discussion is going on in https://www.drupal.org/project/drupal/issues/2867707#comment-12939511 and we should open a dedicated issue for the actual implementation
- The manual conflict resolution as well the route and the controller should live in contrib for now. Since the Conflict module already has a working 8.x-2.x branch, we could either try to put this work into a 8.x-3.x branch, or create a separate contrib, maybe Simple Conflict?

**Comment by amateescu** [comment]
There is also another item here:

- [Revision parameter converter](https://github.com/amateescu/revision_tree/blob/master/src/ParamConverter/RevisionTreeEntityRevisionParamConverter.php)

This is being proposed as a core patch in https://www.drupal.org/project/drupal/issues/2808163

**Comment by amateescu** [comment]
We'll leave this up to the contrib conflict module.
